apiVersion: v1
kind: Pod
metadata:
  name: react-django-pod
  namespace: react-django-app
spec:
  containers:
    - name: react-django-ctr
      image: safiakhatoon/react-django-app:latest
      ports:
        - containerPort: 8001
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
~                             
